baseURL = "https://haani-niyaz.github.io/devops-journal/"
languageCode = "en-us"
title = "DevOps Journal"
theme = "book"
BookRepo = 'https://haani-niyaz.github.io/devops-journal/'
publishDir = "docs"
