baseURL = "https://github.com/haani-niyaz/devops-journal"
languageCode = "en-us"
title = "DevOps Journal"
theme = "book"
BookRepo = 'https://github.com/haani-niyaz/devops-journal'
publishDir = "docs"
